### ISSUE TITLE
Older setuptools causing loading issues

### ISSUE THREAD

**Issue by townie** [Deepwalker/trafaret_forked#64]
Currently on python 2.7 (tested on a RedHat Enterprise Linux 7) pip installing the latest version of trafaret and it no longer loads.

## Steps to Reproduce

```bash
# Separate shell
$ docker run --name rhel7 -v $PWD:/workspace bluedata/rhel7

# Open new shell and run all commands 
$ docker exec -it rhel7 bash
```
# Description:
## Demonstrate failure case
```$ pip install 'trafaret==0.9.1'
$ easy_install --version
setuptools 0.9.8

$ python
>>> import trafaret as t
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/trafaret/__init__.py", line 1558, in <module>
    load_contrib()
  File "/usr/lib/python2.7/site-packages/trafaret/__init__.py", line 1550, in load_contrib
    trafaret_class = entrypoint.resolve()
AttributeError: 'EntryPoint' object has no attribute 'resolve'
```

## Demonstrate upgrade success case
```
# Then run below code 
$ pip install --upgrade setuptools
Collecting setuptools
  Downloading setuptools-35.0.2-py2.py3-none-any.whl (390kB)
...
$ easy_install --version
setuptools 35.0.2 from /usr/lib/python2.7/site-packages (Python 2.7)

$ python
>>> import trafaret as t
>>>
```

**Comment by Deepwalker** [comment]
I will remove this magic from 0.10.0. Too many quirks, and I dont like magic.

**Comment by townie** [comment]
Thanks Deepwalker. Feel free to `@`, I would be glad to test a PR.

**Comment by Deepwalker** [comment]
BTW I did it.
